// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBetSystem {
  function sendMoney() external payable;

  function makeBet(uint256 deltaX, int256 deltaY) external payable returns (bool);

  function resolveBet() external returns (bool);

  function calculateResults(
    uint256 openBet,
    uint256 deltaX,
    int256 deltaY
  ) external view returns (bool[5] memory wentUp, int256 accumulativeDeltaY);

  function getBank() external view returns (uint256);

  function bankHasEnoughFundsForBet(uint256 deltaX, int256 deltaY, uint256 wager) external view returns (bool);

  function getPayout(uint256 wager, uint256 odds) external pure returns (uint256);

  function getOdds(uint256 deltaX, int256 deltaY) external pure returns (uint256);
}
