// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBetSystem {
  function makeBet(uint256 deltaX, int256 deltaY) external returns (bool);

  function resolveBet() external returns (bool);

  function calculateResults(
    uint256 openBet,
    uint256 deltaX,
    int256 deltaY
  ) external returns (bool[] memory wentUp, int256 accumulativeDeltaY);

  function getBank() external returns (uint256);

  function bankHasEnoughFundsForBet(uint256 deltaX, int256 deltaY, uint256 wager) external returns (bool);

  function getPayout(uint256 wager, uint256 odds) external returns (uint256);

  function getOdds(uint256 deltaX, int256 deltaY) external returns (uint256);
}
