/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    OpenBet: (() => {
      const tableId = new TableId("", "OpenBet");
      return defineComponent(
        world,
        {
          open: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Bank: (() => {
      const tableId = new TableId("", "Bank");
      return defineComponent(
        world,
        {
          balance: RecsType.BigInt,
          escrow: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    BetTable: (() => {
      const tableId = new TableId("", "BetTable");
      return defineComponent(
        world,
        {
          player: RecsType.String,
          deltaX: RecsType.BigInt,
          deltaY: RecsType.BigInt,
          result: RecsType.BigInt,
          resolution: RecsType.Number,
          wager: RecsType.BigInt,
          payout: RecsType.BigInt,
          odds: RecsType.BigInt,
          wentUp: RecsType.T,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
