// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

// Import user types
import { BetStatus } from "./../Types.sol";

uint256 constant _tableId = uint256(bytes32(abi.encodePacked(bytes16(""), bytes16("BetTable"))));
uint256 constant BetTableTableId = _tableId;

struct BetTableData {
  uint256 deltaX;
  int256 deltaY;
  BetStatus resolved;
  uint256 wager;
  uint256 odds;
  bool[5] wentUp;
}

library BetTable {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](6);
    _schema[0] = SchemaType.UINT256;
    _schema[1] = SchemaType.INT256;
    _schema[2] = SchemaType.UINT8;
    _schema[3] = SchemaType.UINT256;
    _schema[4] = SchemaType.UINT256;
    _schema[5] = SchemaType.BOOL_ARRAY;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](6);
    _fieldNames[0] = "deltaX";
    _fieldNames[1] = "deltaY";
    _fieldNames[2] = "resolved";
    _fieldNames[3] = "wager";
    _fieldNames[4] = "odds";
    _fieldNames[5] = "wentUp";
    return ("BetTable", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get deltaX */
  function getDeltaX(uint256 block) internal view returns (uint256 deltaX) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 0);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set deltaX */
  function setDeltaX(uint256 block, uint256 deltaX) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.setField(_tableId, _primaryKeys, 0, abi.encodePacked((deltaX)));
  }

  /** Get deltaY */
  function getDeltaY(uint256 block) internal view returns (int256 deltaY) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 1);
    return (int256(uint256(Bytes.slice32(_blob, 0))));
  }

  /** Set deltaY */
  function setDeltaY(uint256 block, int256 deltaY) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.setField(_tableId, _primaryKeys, 1, abi.encodePacked((deltaY)));
  }

  /** Get resolved */
  function getResolved(uint256 block) internal view returns (BetStatus resolved) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 2);
    return BetStatus(uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set resolved */
  function setResolved(uint256 block, BetStatus resolved) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.setField(_tableId, _primaryKeys, 2, abi.encodePacked(uint8(resolved)));
  }

  /** Get wager */
  function getWager(uint256 block) internal view returns (uint256 wager) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 3);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set wager */
  function setWager(uint256 block, uint256 wager) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.setField(_tableId, _primaryKeys, 3, abi.encodePacked((wager)));
  }

  /** Get odds */
  function getOdds(uint256 block) internal view returns (uint256 odds) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 4);
    return (uint256(Bytes.slice32(_blob, 0)));
  }

  /** Set odds */
  function setOdds(uint256 block, uint256 odds) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.setField(_tableId, _primaryKeys, 4, abi.encodePacked((odds)));
  }

  /** Get wentUp */
  function getWentUp(uint256 block) internal view returns (bool[5] memory wentUp) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 5);
    return toStaticArray_bool_5(SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bool());
  }

  /** Set wentUp */
  function setWentUp(uint256 block, bool[5] memory wentUp) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.setField(_tableId, _primaryKeys, 5, EncodeArray.encode(fromStaticArray_bool_5(wentUp)));
  }

  /** Push an element to wentUp */
  function pushWentUp(uint256 block, bool _element) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.pushToField(_tableId, _primaryKeys, 5, abi.encodePacked((_element)));
  }

  /** Get the full data */
  function get(uint256 block) internal view returns (BetTableData memory _table) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _primaryKeys, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(
    uint256 block,
    uint256 deltaX,
    int256 deltaY,
    BetStatus resolved,
    uint256 wager,
    uint256 odds,
    bool[5] memory wentUp
  ) internal {
    bytes memory _data = encode(deltaX, deltaY, resolved, wager, odds, wentUp);

    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.setRecord(_tableId, _primaryKeys, _data);
  }

  /** Set the full data using the data struct */
  function set(uint256 block, BetTableData memory _table) internal {
    set(block, _table.deltaX, _table.deltaY, _table.resolved, _table.wager, _table.odds, _table.wentUp);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal view returns (BetTableData memory _table) {
    // 129 is the total byte length of static data
    PackedCounter _encodedLengths = PackedCounter.wrap(Bytes.slice32(_blob, 129));

    _table.deltaX = (uint256(Bytes.slice32(_blob, 0)));

    _table.deltaY = (int256(uint256(Bytes.slice32(_blob, 32))));

    _table.resolved = BetStatus(uint8(Bytes.slice1(_blob, 64)));

    _table.wager = (uint256(Bytes.slice32(_blob, 65)));

    _table.odds = (uint256(Bytes.slice32(_blob, 97)));

    uint256 _start;
    uint256 _end = 161;

    _start = _end;
    _end += _encodedLengths.atIndex(0);
    _table.wentUp = toStaticArray_bool_5(SliceLib.getSubslice(_blob, _start, _end).decodeArray_bool());
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    uint256 deltaX,
    int256 deltaY,
    BetStatus resolved,
    uint256 wager,
    uint256 odds,
    bool[5] memory wentUp
  ) internal view returns (bytes memory) {
    uint16[] memory _counters = new uint16[](1);
    _counters[0] = uint16(wentUp.length * 1);
    PackedCounter _encodedLengths = PackedCounterLib.pack(_counters);

    return
      abi.encodePacked(
        deltaX,
        deltaY,
        resolved,
        wager,
        odds,
        _encodedLengths.unwrap(),
        EncodeArray.encode(fromStaticArray_bool_5(wentUp))
      );
  }

  /* Delete all data for given keys */
  function deleteRecord(uint256 block) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((block)));

    StoreSwitch.deleteRecord(_tableId, _primaryKeys);
  }
}

function toStaticArray_bool_5(bool[] memory _value) pure returns (bool[5] memory _result) {
  // in memory static arrays are just dynamic arrays without the length byte
  assembly {
    _result := add(_value, 0x20)
  }
}

function fromStaticArray_bool_5(bool[5] memory _value) view returns (bool[] memory _result) {
  _result = new bool[](5);
  uint256 fromPointer;
  uint256 toPointer;
  assembly {
    fromPointer := _value
    toPointer := add(_result, 0x20)
  }
  Memory.copy(fromPointer, toPointer, 160);
}
